//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Seat.Models;
using Exir.Framework.Common;
using FluentValidation;
using Exir.Framework.Security.DataSecurity.Support;
using Exir.Framework.Security.ObjectValidation.Support;


namespace Seat.Validators
{
    public class CodalMessageValidator : AzValidator<CodalMessage>
        {
            public CodalMessageValidator()
            {
    RuleSet(Mode.Any,true, () =>{
    SecurityRuleFor().Allowed(AllFields());
    
    RuleFor(p => p.TracingNo).NotEqual((int)Typing.GetDefaultValue(typeof(int)));
    RuleFor(p => p.Symbol).NotNull().Length(1,100);
    RuleFor(p => p.CompanyName).NotNull().Length(1,100);
    RuleFor(p => p.Title).NotNull().Length(1,1500);
    RuleFor(p => p.SentDateTime).NotEmpty().NotNull();
    RuleFor(p => p.PublishDateTime).NotEmpty().NotNull();
            
    });
    //setBusinessRules();
            }
    
    	private void setBusinessRules()
    		{
    			RuleSet(Mode.OnInsert, () =>
    			{
    				SecurityRuleFor().OperationRequired("CdlMsg.C");
    			});
    
    			RuleSet(Mode.OnBatchRead | Mode.OnSingleRead, () =>
    			{
    				SecurityRuleFor().OperationRequired("CdlMsg.R");
    			});
    
    			RuleSet(Mode.OnUpdate, () =>
    			{
    				SecurityRuleFor().OperationRequired("CdlMsg.U");
    			});
    
    			RuleSet(Mode.OnDelete, () =>
    			{
    				SecurityRuleFor().OperationRequired("CdlMsg.D");
    			});
    		}
        }
    
}
