//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SeatDomain.Models;
using Exir.Framework.Common;
using FluentValidation;
using Exir.Framework.Security.DataSecurity.Support;
using Exir.Framework.Security.ObjectValidation.Support;


namespace SeatDomain.Validations
{
    public class BackstageJobValidator : AzValidator<BackstageJob>
        {
            public BackstageJobValidator()
            {
    RuleSet(Mode.Any,true, () =>{
    SecurityRuleFor().Allowed(AllFields());
    
    RuleFor(p => p.RunAs).NotNull().Length(1,70);
    RuleFor(p => p.TimeToRun).NotEmpty().NotNull();
    RuleFor(p => p.Status).LessThanOrEqual(Int16.MaxValue).GreaterThanOrEqual(Int16.MinValue).NotEmpty();
    RuleFor(p => p.Service).NotNull().Length(1,100);
    RuleFor(p => p.Action).NotNull().Length(1,100);
    RuleFor(p => p.RetryCount).LessThanOrEqual(Byte.MaxValue).GreaterThanOrEqual(Byte.MinValue).NotEmpty();
    RuleFor(p => p.Priority).LessThanOrEqual(Int16.MaxValue).GreaterThanOrEqual(Int16.MinValue).NotEmpty();
    RuleFor(p => p.UniqueCode).Length(0,50);
    RuleFor(p => p.Dependency).Length(0,50);
    RuleFor(p => p.Queue).Length(0,50);
    RuleFor(p => p.Server).Length(0,50);
    RuleFor(p => p.Tags).Length(0,50);
    RuleFor(p => p.MaxCpu).LessThanOrEqual(Byte.MaxValue).GreaterThanOrEqual(Byte.MinValue);
    RuleFor(p => p.MaxMemory).LessThanOrEqual(Byte.MaxValue).GreaterThanOrEqual(Byte.MinValue);
    RuleFor(p => p.MidCpu).LessThanOrEqual(Byte.MaxValue).GreaterThanOrEqual(Byte.MinValue);
    RuleFor(p => p.MidMemory).LessThanOrEqual(Byte.MaxValue).GreaterThanOrEqual(Byte.MinValue);
            
    });
    setBusinessRules();
            }
    		 private void setBusinessRules()
            {
                RuleSet(Mode.OnInsert | Mode.OnDelete | Mode.OnUpdate, () =>
                  {
                      SecurityRuleFor().OperationRequired("BckstgJb.A");
                  });
            }
    	
        }
    
}
