//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SeatDomain.Models;
using Exir.Framework.Common;
using FluentValidation;
using Exir.Framework.Security.DataSecurity.Support;
using Exir.Framework.Security.ObjectValidation.Support;


namespace SeatDomain.Validations
{
    public class SystemMessageValidator : AzValidator<SystemMessage>
        {
            public SystemMessageValidator()
            {
    RuleSet(Mode.Any,true, () =>{
    SecurityRuleFor().Allowed(AllFields());
    
    RuleFor(p => p.Code).NotNull().Length(1,50);
    RuleFor(p => p.Subject).NotNull().Length(1,2000);
    RuleFor(p => p.Text).NotNull();
    RuleFor(p => p.Media).NotNull().Length(1,10);
    RuleFor(p => p.Culture).NotNull().Length(1,5);
    RuleFor(p => p.Audit_CreatorUserName).NotNull().Length(1,50);
    RuleFor(p => p.Audit_CreatorIP).NotNull().Length(1,50);
    RuleFor(p => p.Audit_CreateDate).NotEmpty().NotNull();
    RuleFor(p => p.Audit_LastModifyDate).NotEmpty().NotNull();
    RuleFor(p => p.Audit_LastModifierUserName).NotNull().Length(1,50);
    RuleFor(p => p.Audit_LastModifierIP).NotNull().Length(1,50);
            
    });
    setBusinessRules();
            }
    		 private void setBusinessRules()
            {
                RuleSet(Mode.OnInsert | Mode.OnDelete | Mode.OnUpdate, () =>
                  {
                      SecurityRuleFor().OperationRequired("SystmMsg.A");
                  });
            }
    	
        }
    
}
